CREATE TABLE `pages` (
	`page_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
	`header` VARCHAR(255) NULL DEFAULT NULL,
	`body` TEXT NULL,
	`body_ext` TEXT NULL,
	`created` DATETIME NULL DEFAULT NULL,
	`changed` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`page_id`)
)
ENGINE=InnoDB;
